# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTdkOTg0MzljZTIwZmZkNmE4NWJmODVhNzY2YWU4MDk3ODg3Mjg3NTZmMjQyMGM2OTE3ZDQxZjZjMzEyNTNhMmIxNDZjODc2MDNlMDE5MDRhY2I0YWRkMGVhZGJjZjA5M2YxMTA5OTVmZGY0NDk3ZTNhMzBkYTM0ZTg3Y2Y4MTI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
